Beers/Models/Beer.cs
using System.ComponentModel.DataAnnotations;

namespace Drinks.Models
{
    public class Beer
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public BeerType Type { get; set; }
    }
}

Beers/Models/BeerType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Models
{
    public enum BeerType
    {
        None,
        Blonde,
        Dark,
        Tripple,
        Quadruple
    }
}

Beers/Models/Whiskey.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Models
{
    public class Whiskey
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public WhiskeyType Type { get; set; }
    }
}

Beers/Models/WhiskeyType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Models
{
    public enum WhiskeyType
    {
        None,
        SingleMalt,
        Scotch,
        GrainWhisky,
        BlendedWhisky
    }
}

Beers/ViewModels/BeerEditModel.cs
using Drinks.Models;
using System.ComponentModel.DataAnnotations;

namespace Drinks.ViewModels
{
    public class BeerEditModel
    {
        [Required]
        public string Name { get; set; }
        public BeerType Type { get; set; }
    }
}

Beers/ViewModels/BeerIndexViewModel.cs
using Drinks.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.ViewModels
{
    public class BeerIndexViewModel
    {
        public IEnumerable<Beer> Beers { get; set; }
    }
}

Beers/ViewModels/HomeIndexViewModel.cs
using Drinks.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Beer> Beers { get; set; }
    }
}

Beers/ViewModels/WhiskeyEditModel.cs
using Drinks.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.ViewModels
{
    public class WhiskeyEditModel
    {
        [Required]
        public string Name { get; set; }
        public WhiskeyType Type { get; set; }
    }
}

Beers/ViewModels/WhiskeyIndexViewModel.cs
using Drinks.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.ViewModels
{
    public class WhiskeyIndexViewModel
    {
        public IEnumerable<Whiskey> Whiskies { get; set; }
    }
}

Beers/Controllers/BeerController.cs
using Drinks.Models;
using Drinks.Services;
using Drinks.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Controllers
{
    public class BeerController : Controller
    {
        private IBeerData _beerData;

        public BeerController(IBeerData beerData)
        {
            _beerData = beerData;
        }

        public IActionResult Index()
        {
            var model = new BeerIndexViewModel();

            model.Beers = _beerData.GetAll();

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _beerData.Get(id);

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(BeerEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newBeer = new Beer();
                newBeer.Name = model.Name;
                newBeer.Type = model.Type;

                newBeer = _beerData.Add(newBeer);

                return RedirectToAction("Details", new { Id = newBeer.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

Beers/Controllers/HomeController.cs
using Drinks.Models;
using Drinks.Services;
using Drinks.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Beers/Controllers/WhiskeyController.cs
using Drinks.Models;
using Drinks.Services;
using Drinks.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drinks.Controllers
{
    public class WhiskeyController : Controller
    {
        private IWhiskeyData _whiskeyData;

        public WhiskeyController(IWhiskeyData whiskeyData)
        {
            _whiskeyData = whiskeyData;
        }

        public IActionResult Index()
        {
            var model = new WhiskeyIndexViewModel();

            model.Whiskies = _whiskeyData.GetAll();

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _whiskeyData.Get(id);

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(WhiskeyEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newWhiskey = new Whiskey();
                newWhiskey.Name = model.Name;
                newWhiskey.Type = model.Type;

                newWhiskey = _whiskeyData.Add(newWhiskey);

                return RedirectToAction("Details", new { Id = newWhiskey.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

Beers/Views/Beer/Create.cshtml
@using Drinks.Models
@model Beer

@{
    ViewBag.Title = "Add a new Beer to the list";
}

<h1>Create</h1>

<form method="post">
    <table>
        <tr>
            <td>
                <label asp-for="Name"></label>
                <input asp-for="Name" value="" />
                <span asp-validation-for="Name"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Type"></label>
                <select asp-for="Type" asp-items="@Html.GetEnumSelectList<BeerType>()"></select>
                <span asp-validation-for="Type"></span>
            </td>
        </tr>
    </table>


    <input type="submit" name="save" value="Save" />
</form>

Beers/Views/Beer/Details.cshtml
@model Drinks.Models.Beer

@{
    ViewBag.Title = "Details of " + Model.Name;
}

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Type: @Model.Type
</div>
<a asp-action="Index" asp-controller="Home">Home</a>

Beers/Views/Beer/Index.cshtml
@model Drinks.ViewModels.BeerIndexViewModel

@{
    ViewBag.Title = "List of Beers";
}


<table>
    @foreach (var beer in Model.Beers)
    {
        <tr>
            <td>ID: @beer.Id</td>
        </tr>
        <tr>
            <td>Name: @beer.Name</td>
        </tr>
        <tr>
            <td>Type: @beer.Type</td>
        </tr>
        <tr>
            <td><a asp-action="Details" asp-route-id="@beer.Id">Details</a></td>
        </tr>
    }
</table>
<a asp-action="Create">Add a beer to the list</a>

Beers/Views/Home/Create.cshtml
@using Drinks.Models
@model Beer

<h1>Create</h1>

<form method="post">
    <table>
        <tr>
            <td>
                <label asp-for="Name"></label>
                <input asp-for="Name" value="" />
                <span asp-validation-for="Name"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Type"></label>
                <select asp-for="Type" asp-items="@Html.GetEnumSelectList<BeerType>()"></select>
                <span asp-validation-for="Type"></span>
            </td>
        </tr>
    </table>
    

    <input type="submit" name="save" value="Save" />
</form>

Beers/Views/Home/Details.cshtml
@model Drinks.Models.Beer

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Type: @Model.Type
</div>
<a asp-action="Index" asp-controller="Home">Home</a>

Beers/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home page";
}

<a asp-action="Index" asp-controller="Beer">Beers drinks</a>
<a asp-action="Index" asp-controller="Whiskey">Whiskey drinks</a>

Beers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Beers/Views/Whiskey/Create.cshtml
@using Drinks.Models
@model Whiskey

@{
    ViewBag.Title = "Add a new Whiskey to the list";
}

<h1>Create</h1>

<form method="post">
    <table>
        <tr>
            <td>
                <label asp-for="Name"></label>
                <input asp-for="Name" value="" />
                <span asp-validation-for="Name"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Type"></label>
                <select asp-for="Type" asp-items="@Html.GetEnumSelectList<WhiskeyType>()"></select>
                <span asp-validation-for="Type"></span>
            </td>
        </tr>
    </table>


    <input type="submit" name="save" value="Save" />
</form>

Beers/Views/Whiskey/Details.cshtml
@model Drinks.Models.Whiskey

@{
    ViewBag.Title = "Details of " + Model.Name;
}

<h1>@Model.Name</h1>
<div>
    Id: @Model.Id
</div>
<div>
    Type: @Model.Type
</div>
<a asp-action="Index" asp-controller="Home">Home</a>

Beers/Views/Whiskey/Index.cshtml
@model Drinks.ViewModels.WhiskeyIndexViewModel

@{
    ViewBag.Title = "List of Whiskies";
}

<table>
    @foreach (var whiskey in Model.Whiskies)
    {
        <tr>
            <td>ID: @whiskey.Id</td>
        </tr>
        <tr>
            <td>Name: @whiskey.Name</td>
        </tr>
        <tr>
            <td>Type: @whiskey.Type</td>
        </tr>
        <tr>
            <td><a asp-action="Details" asp-route-id="@whiskey.Id">Details</a></td>
        </tr>
    }
</table>
<a asp-action="Create">Add a Whiskey to the list</a>